### ISSUE TITLE
Module Definition Problem

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu-odata#1]
Hi,

The most recent version of the jinqu-data package deployed to npm seems to have a module definition problem.

To reproduce, here's a stackblitz sample, which merely tries to import the package:
https://stackblitz.com/edit/min-dmmjuy?file=index.ts

As you can see, it fails to import.

Thanks,
Ben

**Comment by umutozel** [comment]
Hi,

Good catch, I think with last alpha package, pre-publish command did not work, so we released a package without any code. Fixed with alpha.4.

Thanks.
