### ISSUE TITLE
Boilerplate removal

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu-odata#11]
Just in case you dislike boilerplate and you're not aware of this, Typescript has an unusual but convenient feature where a class is also implicitly an interface. This means you can define an interface by extending a class.

So in this code:
https://github.com/jin-qu/jinqu-odata/blob/master/test/fixture.ts

Instead of:
```typescript
export interface ICompany {
    id: number;
    name: string;
    deleted: boolean;
    createDate: Date;
    addresses: Address[];
}

export class Company implements ICompany {
    id: number;
    name: string;
    deleted: boolean;
    createDate: Date;
    addresses: Address[];
}
```
You can just go:
```typescript
export class Company {
    id: number;
    name: string;
    deleted: boolean;
    createDate: Date;
    addresses: Address[];
}
export interface ICompany extends Company { }
// now can use ICompany as an interface
```

**Comment by umutozel** [comment]
I didn't know that, TypeScript keeps surprising me.
