### ISSUE TITLE
Example of Expand + Select

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu-odata#15]
Submitted the pull request for updated docs, but one thing that's absent in the new docs is the section explaining how to combine expands with selects.

That section was:
```
// with selects
const result = query
    .expand(c => c.addresses)
        .thenExpand(a => a.city, a => a.country)
    .expand(c => c.addresses.$expand(a => a.city).country, c => c.name);
// $expand=addresses($expand=city($expand=country($select=name),$select=country),$select=city)
```
Not sure how to code that with the new API.

Current working expand demo is here: 
https://stackblitz.com/edit/jinqu

**Comment by umutozel** [comment]
This looks like a bug, we should use selected value as returned query's generic argument.

**Comment by umutozel** [comment]
But of course we can ignore this and believe in the developer.

**Comment by umutozel** [comment]
I wanted to fix the docs, but didn't want to add a random property to **Author**. Is there any navigation we can use on **Author** type? I checked the network on stackblitz, and it seems Author only have Id and Name.

**Comment by solenya-group** [comment]
The schema is:
https://www.solenya.org/odata/$metadata

It originally came from a Microsoft sample, but I've extended it to handle the more complex scenario of an author with multiple books. Can continue to extend it. If an author had an address, would that be useful to demonstrate the scenario?

**Comment by umutozel** [comment]
Yeah, that would be great.

**Comment by umutozel** [comment]
Implemented a test function like this:

```typescript
select<K extends keyof T>(...names: K[]): Pick<T, K>

// usage
const c = service.companies().select('addresses', 'createDate')
// c only have 'addresses' and 'createDate' properties
```

I'm not sure if we should prefer this. It would force users to avoid invalid projection expression. Also still type safe.

**Comment by solenya-group** [comment]
OK, I'll add the Address field shortly.

**Comment by solenya-group** [comment]
There's now an "Address" property on Author. Note Address is a complex type, so does not have a key, but should be fine for the expand scenario.

I've also removed the "Location" (of type address) property from Book, as this didn't really seem to make sense (surely a Press or an Author would have an address, not a book).

The metadata:
https://www.solenya.org/odata/$metadata

**Comment by umutozel** [comment]
I think `Address` being complex type causes problems with $expand.

```
Books?$expand=AuthorBooks($expand=Author($expand=Address))

// The query specified in the URI is not valid. Property 'Address' on type 'Default.Author' is not a navigation property or complex property. Only navigation properties can be expanded.
```

**Comment by solenya-group** [comment]
Will have a look

**Comment by solenya-group** [comment]
There's something weird going on; you should be able to expand complex types. Investigating.

**Comment by solenya-group** [comment]
As far as I can tell, the behaviour of ASP.NET's Core OData implementation, is that complex types are automatically returned, with the caveat that they're omitted if they exceed the MaxExpansionDepth value.

So will come up with an alternative to Address shortly.

**Comment by umutozel** [comment]
It's weird indeed, but expected. A standard like this shouldn't change from implementation to implementation.

**Comment by solenya-group** [comment]
OK, Authors now have a Nationality:

https://www.solenya.org/odata/Books?$expand=AuthorBooks($expand=Author($expand=Nationality))

Regarding complex types, I did more testing, and MaxExpansionDepth doesn't actually have an affect on complex types. The reason the Address was showing up as null was due to some other bug. They should always be returned with the entity.

**Comment by solenya-group** [comment]
Where the type of `Nationality` is `Country`. Perhaps later to test additional scenarios can add a "Country" reference to Address; I think that's actually a legitimate OData schema.

**Comment by umutozel** [comment]
Super, maybe we can replace test metadata with your schema. I will look into it.

**Comment by umutozel** [comment]
All completed. Here is a sample (from unit tests)

```typescript
const id = 42;
const query = service.companies()
    .expand('addresses', ['city'])
    .expand('addresses', a => a.id > id, { id })
        .thenExpand('city', c => c.name == 'Gotham')
            .thenExpand('country');

// $expand=addresses($filter=id gt 42;$expand=city($filter=name eq 'Gotham';$expand=country))
```

All type-safe, including 'addresses' and ['city'] part.

**Comment by solenya-group** [comment]
Updated docs accordingly:
https://github.com/jin-qu/jinqu-odata/pull/17
