### ISSUE TITLE
Expand Design

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu-odata#2]
Nice library.

I noticed the design of `expand` is similar to the old version of Entity Framework's `include`, in terms of how nested queries work. In Entity Framework Core, they introduced the `ThenInclude` extension. Seems the equivalent for jinqu would be `ThenExpand`. Then the Array prototype wouldn't need to be touched.

Thanks,
Ben

**Comment by umutozel** [comment]
This is a great idea, I forgot about `ThenInclude`, I will implement it as soon as possible, will close the issue when it's completed.

**Comment by umutozel** [comment]
Completed, removed `$expand` from Array proto.
published alpha.5 package. Thanks again for the suggestion.
If there is any problem we can re-open the issue.

**Comment by solenya-group** [comment]
Just tried updating the sample and ran into a problem with `expand`, though my best guess is this is a problem with the odata syntax generated (possibly a version issue), as opposed to a problem with the latest change.

Here's the expand / thenExpand query that doesn't work:
https://stackblitz.com/edit/jinqu

Looking at the the network call, the issue appears to be:

```
https://www.solenya.org/odata/Books?$expand=AuthorBooks($expand=Author) // this should be called
https://www.solenya.org/odata/Books?$expand=AuthorBook%2FAuthor // instead this is called
```

**Comment by umutozel** [comment]
Great news. I'm closing the issue for now.
