### ISSUE TITLE
createQuery with classes

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu-odata#3]
How can `createQuery` handle types that are classes?

The problem is that it merely takes a generic argument, and the generic type only exists at compile time, not runtime. Instead, for `createQuery` to work with classes, that type would have to be passed as a *constructor*.

Specifically:

```typescript
createQuery<Company>("company") // can't work with classes
createQuery(Company, "company") // works with classes
```

To make the class version work, the `class-transformer` package or similar serialization package would be required. Very useful as it eliminates the extra step / boilerplate to deserialize the plain objects into classes.

Thanks,
Ben

**Comment by umutozel** [comment]
This also is a great idea. I thought duck typing would be enough for classes, but we can get benefits from it, fixing prototype would be great. I remember some of old hacks wouldn't be necessary with this 💯

**Comment by solenya-group** [comment]
Workaround for now:

```typescript
const query = await createQuery<any>("company")
const array = plainToClass (Company, await query.toArrayAsync())
```

Just thinking out loud... perhaps a deserializer should be coupled to a particular `IRequestProvider` instance, that `createQuery` would delegate to. Something like:

```typescript
export class MyService extends ODataService
{
  // this is defined in ODataService base class; throws exception by default
  deserialize<T> (constructorRef : new() => T, rawText: string) {
    // now deserialize using the serialization engine we want; this uses class-transformer
    return deserializeArray (constructorRef, rawText, myDeserializationOptions)
  }
  ...
}

// can now go
const query = await createQuery (Company, "company")
```
Where possibly calling `createQuery` with the constructor argument, where `deserialize` hasn't been overridden, gives you a helpful not implemented exception, i.e. tells you need to implement `deserialize`, else just use the overload of `createQuery` that doesn't return classes. Also, I'm a bit fuzzy on the rules for typescript overloading, so not sure if createQuery can/should be overloaded with the version that works with non-class instances, or whether a separately named method makes sense.

**Comment by umutozel** [comment]
Maybe we can add a new chain method, like;

`
withType<T>(type: new() => T);
`

But I will try to add this to base query. I am working on `expand` for now, but I will try to look at this before weekend.

**Comment by solenya-group** [comment]
At the risk of interrupting your flow, have a couple more thoughts.

With classes, there's also the benefit you can now leverage either the name of the class, or a decorator on that class. I.e.

```typescript
// instead of:
createQuery (Company, "company")

// you can just go:
createQuery (Company)

// where:
class Company {...}

// or to specialize the name:
@Table("companies")
class Company {...}
```

In another library, I'm using this exact strategy for display names for properties. 80%-90% of the time, the property name (w/ a strategy like capitalizing the first letter) is used. The remaining 10-20% of the time, the @Label (text: string) decorator allows the label text to be customized. Very convenient.

Also note that with classes, you can leverage inheritance to address the occasional scenario where two endpoints/tables have the same structure, i.e. there's a 1-1 mapping between class names and endpoints/table names (this assumption works fine in a typical ORM).

**Comment by umutozel** [comment]
No problem.
Yeah this could simplify things, I too tried using `toString()` and some RegEx to get class/function name from a parameter from a call like `createQuery(Company)`, but minifiers do their stuff and complicates things. Most of the time we had to use your first overload, like AngularJS modules.

But decorators might be cool. We could fall back to its name when decorator is missing, and have settings like `pluralize` or `lowercase`. 
I always consider jinqu to be a good candidate for a ORM's base library, and Model Driven approach would really simplify things.

Btw, I created a PR for Swagger code generator, but didn't get through. I wanted to have a code generator for service definitions (using metadata), god I hate boilerplate code. Still considering options.

**Comment by umutozel** [comment]
> Workaround for now:
> 
> ```ts
> const query = await createQuery<any>("company")
> const array = plainToClass (Company, await query.toArrayAsync())
> ```
> 
> Just thinking out loud... perhaps a deserializer should be coupled to a particular `IRequestProvider` instance, that `createQuery` would delegate to. Something like:
> 
> ```ts
> export class MyService extends ODataService
> {
>   // this is defined in ODataService base class; throws exception by default
>   deserialize<T> (constructorRef : new() => T, rawText: string) {
>     // now deserialize using the serialization engine we want; this uses class-transformer
>     return deserializeArray (constructorRef, rawText, myDeserializationOptions)
>   }
>   ...
> }
> 
> // can now go
> const query = await createQuery (Company, "company")
> ```
> 
> Where possibly calling `createQuery` with the constructor argument, where `deserialize` hasn't been overridden, gives you a helpful not implemented exception, i.e. tells you need to implement `deserialize`, else just use the overload of `createQuery` that doesn't return classes. Also, I'm a bit fuzzy on the rules for typescript overloading, so not sure if createQuery can/should be overloaded with the version that works with non-class instances, or whether a separately named method makes sense.

I forgot to write, I believe setting prototype for every item in the result with `Object.setPrototypeOf` with given ctor would be enough to fix type detachment. Of course only when no `select`, `groupBy` or any other type modifier used.
Maybe we could also check `$type` field to be sure the type is correct. But I'm not sure if this field is standard among the JSON serializers or only a JSON.Net approach.

**Comment by umutozel** [comment]
Thank you for your feedbacks, really, helping a lot and I'm gaining new perspectives.

You are right, shallow proto fixing is not enough, I used this technique few years back to trick KendoUI to thinking my object is observable so it doesn't wrap it (it can't handle circular deps).
I was looking into class-transformer when I see your comment, it looks great. I might have to change ajax-provider logic though, because I left deserializing to IAjaxProvider implementations (I expect raw objects as result). Thinking about this on another thread.

And maybe we can get final type when executing the query, like `toArrayAsync(type?: new() => T)`. This way we can know the correct type for sure.

I used to rely on `$type` property heavily on another really old project of mine (beetle.js). In fact, most of my recent projects are inspired from beetle.js (like decomposing an old monolith). I think I really want Linq and Entity Framework in my TypeScript.

> I don't think it's standard, but it's really nice when it's there (there's no other way to handle polymorphic arrays). JSON.net even has a format for circular references.

Best to avoid $type altogether. I have a JavaScript project that generates exact JSON as JSON.Net does for circular references. So I can safely serialize/deserialize objects on frontend and backend.

> I can't stand boilerplate either. So you need to scan an odata metadata xml file, and produce some typescript definitions? Sounds like something that could be coded in a single expression...

I was too lazy to use odata metadata to create code, I tried only with Swagger metadata, they have really great base types, you provide some mustache template and override a few methods and voila you have a generator. Tricky part was adding a working Swagger endpoint to an Asp.Net Core OData service. I parked that code generation thoughts for now.

**Comment by solenya-group** [comment]
Here's a quick prototype odata schema to typescript class generator:
https://stackblitz.com/edit/odata

Don't see any major difficulties fleshing this out.

**Comment by umutozel** [comment]
I started the development of type aware queries. But I decided to add this feature to `jinqu`, this way every other project that uses `jinqu` infrastructure will have this ability (`jinqu` itself, `linquest`, `jinqu-odata`..)

**Comment by umutozel** [comment]
After this issue is completed, I really want to work on code generation. We will discuss it later if it's ok with you.

**Comment by solenya-group** [comment]
No problem.

**Comment by umutozel** [comment]
Done. alpha.7 package published.

We have a few way to set the .ctor:

```typescript
// when creating a query
const result = await svc.createQuery<ICompany>('companies', Company).toArrayAsync();
// when executing a query
const result = await svc.createQuery<ICompany>('companies').toArrayAsync(Company);
// when executing a select
const query = svc.createQuery<{ company: ICompany }>('companies');
const result = await query.select<ICompany>(d => d.company, Company);
```

I will do the same development for `linquest` project.

Now we are one step closer for Decorators.

**Comment by solenya-group** [comment]
Hey I'm getting the module error problem on the stackblitz sample with the latest version of jinqu-odata...

**Comment by umutozel** [comment]
I have an external script that compiles TypeScript, bumps version and publishes to npm.
I belive there is a problem with that, only manual publishes worked, really sorry.

I didn't want to use prepublish script to compile, it breaks the coverage report on coveralls.

I've just manually published alpha.8, should work now. And I will find a permanent solution to this problem.

**Comment by solenya-group** [comment]
Great, that works.

I've updated https://stackblitz.com/edit/jinqu?file=index.ts so that the `createQuery` usage is now:
.createQuery("Books", Book)

As soon as you have decorators enabled I'll update the sample accordingly.
