### ISSUE TITLE
Creating Jinqu Angular HttpClient Ajax provider

### ISSUE THREAD

**Issue by buchatsky** [jin-qu/jinqu-odata#36]
## Jinqu Angular HttpClient Ajax provider
Passing OData queries through Angular HttpClient
```
import { Injectable } from "@angular/core";
import { HttpClient } from "@angular/common/http";
import { ODataService } from 'jinqu-odata';

import { AngularHttpProvider } from 'jinqu-ng-http';
import { Product } from './models';

@Injectable()
export class NorthwindContext extends ODataService {
  constructor(http: HttpClient) {
    super('odata/', new AngularHttpProvider(http));
  }

  get products() { return this.createQuery<Product>('products'); }
}
```

**Comment by buchatsky** [comment]
I've already implemented it: [jinqu-ng-http](https://github.com/buchatsky/jinqu-ng-http)

- Tests are written with jasmine (I failed to use mocha because it complained at zone.js)
- withCredentials option is not used because it is absent in AjaxOptions

@umutozel you may copy or fork the repository and take over the ownership, I left your name as a package owner

**Comment by umutozel** [comment]
Thank you for the Angular implementation.
My main goal to seperate providers entirely to make it possible for everyone to create a new one, so it can stay as it is.
Btw I plan to switch to jasmine too.

**Comment by buchatsky** [comment]
Published under my name at https://registry.npmjs.org/ts-odata-model-gen
