### ISSUE TITLE
select(...names) to return IODataQuery instead of executing query

### ISSUE THREAD

**Issue by buchatsky** [jin-qu/jinqu-odata#42]
## Expected  behavior
Getting an instance of IODataQuery<Pick<T, K>, TExtra> as a result of query.select(...names), in order to make a chain of query clauses in arbitrary order:
```
    let result = await this.context.products()
                .select('ProductId', 'ProductName', 'UnitPrice')
                .where(p => p.UnitPrice ? p.UnitPrice > 100.00 : false)
                .inlineCount()
                .toArrayAsync();

```
## Actual behavior
query.select(...names) performs a real query to the OData service and returns a Promise, so it must be the last clause in the chain.

## jinqu-odata version: 1.1.3

**Comment by buchatsky** [comment]
I created a [pull request](https://github.com/buchatsky/jinqu-odata/pull/1) in my own repository. Unfortunately I cannot create a chained PR in the original repo before my first PR is merged

**Comment by umutozel** [comment]
Sorry for the delayed merges, I think it's best to use the PR from your repo 👍

**Comment by buchatsky** [comment]
Is already made: [PR](https://github.com/jin-qu/jinqu-odata/pull/45)
(changes to package.json are unnecessary - that was a mess with versions)

**Comment by buchatsky** [comment]
I managed to implement .select as follows:
```
.select(p => [p.ProductId, p.ProductName, p.UnitPrice])
```
<strike>If you find it useful you can merge it too/ Again, it is close to Simple.OData.Client.</strike>

Hold on, probably this is wrong because beetle.js did allow object syntax:
`.select(b => { b.Id, b.ISBN, b.Title, b.Author });`

**Comment by buchatsky** [comment]
Array notation didn't work. I think that for now it is enough with .select()
