### ISSUE TITLE
String filters should use single quotes

### ISSUE THREAD

**Issue by TheoBP** [jin-qu/jinqu-odata#6]
E.g. filters such as:

```typescript
      .where(b => b.Title == "C# 7.0 in a Nutshell")
```

Currently generates:
https://www.solenya.org/odata/Books?$expand=AuthorBooks(%24expand%3DAuthor)&$orderby=Title&$filter=Title%20eq%20%22C%23%207.0%20in%20a%20Nutshell%22

But should generate:
https://www.solenya.org/odata/Books?$expand=AuthorBooks(%24expand%3DAuthor)&$orderby=Title&$filter=Title%20eq%20%27C%23%207.0%20in%20a%20Nutshell%27

**Comment by umutozel** [comment]
Totally my mistake, should've used `'` for strings.
I'm on it, probably will publish after class prototype fix issue completed.

**Comment by TheoBP** [comment]
Awesome. Great project by the way!

**Comment by umutozel** [comment]
Thank you very much!
(almost finished, just adding some tests)

**Comment by umutozel** [comment]
Done. alpha.7 package published.
