### ISSUE TITLE
ODataService.request: removing all @odata metadata fields was a wrong decision

### ISSUE THREAD

**Issue by buchatsky** [jin-qu/jinqu-odata#60]
First, if it is done, is should be done recursively, not only on single entity, but also on arrays.
And second, it should not be done at all, because e.g. @odata.etag is required for optimistic concurrency when RowVersion field is not included in $select clause or is not present in DTO model.
Presence of odata metadata in response should be controlled by "metadata" param of "accept" http header. It may be a param in ODataService constructor

**Comment by AimTune** [comment]
Recent changes did not take effect in the npm package. You can check out the example below.

![image](https://github.com/jin-qu/jinqu-odata/assets/7990795/cb0237ef-cb72-4fc7-b7b6-e2bea14afc20)

![image](https://github.com/jin-qu/jinqu-odata/assets/7990795/93af2800-32e5-4989-a52a-85b6a06ac9a1)

**Comment by buchatsky** [comment]
It probably fixed the contradiction between github and npmjs sources, but not the issue with functionality itself.
pr#82 fixes it (preserves odata metadata in the resulting object)

**Comment by AimTune** [comment]
> It probably fixed the contradiction between github and npmjs sources, but not the issue with functionality itself. pr#82 fixes it (preserves odata metadata in the resulting object)

The npm package is not updated because the npm token is not defined under Github Actions Secrets.

**Comment by buchatsky** [comment]
@AimTune That was not the point of this issue. The point was to remove back the code that cleared metadata and leave it as it was before
